version: '3.7'

services:
  postgres:
    image: postgres
    container_name: sb_postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - default

  my_pyspark_container:
    image: sb_pyspark_app
    container_name: sb_pyspark_container
    volumes:
      - ./host_output:/app/output
      - ./host_input:/app/input/
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    networks:
      - default